
//This file has been automatcally generated by pngconverter utility
//Please do not edit
#ifndef IMG1_V_H
#define IMG1_V_H

#include "mxgui/image.h"

extern const mxgui::Image img1_v;

#endif //IMG1_V_H
