
//This file has been automatcally generated by pngconverter utility
//Please do not edit
#ifndef IMG1_H_H
#define IMG1_H_H

#include "mxgui/image.h"

extern const mxgui::Image img1_h;

#endif //IMG1_H_H
