
//This file has been automatcally generated by pngconverter utility
//Please do not edit
#ifndef IMG2_H_H
#define IMG2_H_H

#include "mxgui/image.h"

extern const mxgui::Image img2_h;

#endif //IMG2_H_H
