
//This file has been automatcally generated by pngconverter utility
//Please do not edit
#ifndef IMG2_V_H
#define IMG2_V_H

#include "mxgui/image.h"

extern const mxgui::Image img2_v;

#endif //IMG2_V_H
